### ISSUE TITLE
Problem installing spacy

### ISSUE THREAD

**Issue by pma2** [LDSSA/batch2-blu08#2]
Anaconda does not want to install spacy... any suggestions?
Thanks
Windows 10, Anaconda 1.8.7
Note: althougth the message says removing, actualy only spacy is marked for install (not for removal).
![image](https://user-images.githubusercontent.com/38791092/42736989-e17b0c90-8866-11e8-9a2d-33b70619df19.png)

**Comment by PedroMLF** [comment]
Did you use the exact command they suggest in spacy website?

```
conda install -c conda-forge spacy
```

**Comment by pma2** [comment]
... now I did 👍 
And it worked. I think it downgraded Anaconda package, in fact more than 10 packages. Working now.
